### PR TITLE
Upstream onboarding for Emerald

### PR DESCRIPTION
**Pull request by rustyjux**
and a little restructuring of the upstream service config page while we are at it.

For APS-3042

### CODE REVIEW

**Comment by rustyjux** [comment]
@ikethecoder wrote in chat:
> sometime, lets review together https://github.com/bcgov/aps-infra-platform/blob/upstream-onboarding/documentation/how-to/upstream-services.md  - I split the content out by cluster as there are some growing differences between them.. rather than how it was as a single process with mentions of exceptions.. I'm not sold necessarily on the split by cluster but wanted to get your view - to me it does have some duplication but it's cleaner

My reply:
I'm sold on your approach. I did a little refinement and deployed to https://dev.developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs/how-to/upstream-services. I left the old stuff in appendix to allow comparison.

The only thing that might have been dropped from the previous content is the pointer to private routes. Could add as a next step.

---
so do we want to go ahead with the new split-by-cluster approach?

**Comment by ikethecoder** [comment]
Yep, and I pulled out the other way and put it into a temp file - fine to just delete it if you want - I added some content related to private routes to the new doc.

**Comment by rustyjux** [comment]
Repetitive but appropriately placed and short enough. I like it.

**Review by Elson9 — APPROVED** [review]

**Comment by rustyjux** [comment]
I'm going to delete the old content because it pops up in search

**Pull request merged**
